baseURL = 'https://adrian.pw/'
languageCode = 'en-us'
title = 'apw'
theme = 'gioia'
relativeURLs = true

author = "Adrian Price-Whelan"

## Hugo Built-in Features
googleAnalytics = "UA-11936482-16"
pluralizelisttitles = "false"

## Site Settings
[params]
  author = "Adrian Price-Whelan"
  intro = "astronomy & open-source software"
  # description = "astronomy, software, music"
  front_image = "m31-orbits.png"
  dateformat = "2006-01-02"

## Site Meta Settings
[params.meta]
  description = "Simple minimalist theme"
  keywords = "minimalist,blog,goa,hugo,developer"

## Social Accounts
[params.social]
  github = "adrn"
  twitter = "adrianprw"
  googlescholar = "_wSmxLcAAAAJ"
  orcid = "0000-0003-0872-7098"
  email = "adrianmpw@gmail.com"

## Extras
[params.extra]
  copyright = "© 2015-2024 Adrian Price-Whelan"
  prismjs = true
  socialmarkup = false
  toc = true
  footer = "Reach me at adrianmpw@gmail.com"

## Main Menu
[[menu.main]]
    name = "about"
    identifier = "about"
    weight = 100
    url = "/about/"
[[menu.main]]
    name = "cv"
    weight = 200
    identifier = "cv"
    url = "http://adrian.pw/cv/PriceWhelan-cv.pdf"
[[menu.main]]
    name = "blog"
    weight = 300
    identifier = "blog"
    url = "/blog/"
[[menu.main]]
    name = "research"
    weight = 400
    identifier = "research"
    url = "/research/"
[[menu.main]]
    name = "visualizations"
    weight = 500
    identifier = "visualizations"
    url = "/viz/"

[markup]
  [markup.highlight]
    codeFences = false

  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true