name: Build site

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    concurrency: build-${{ github.ref }}
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Python dependencies
        run: python -m pip install requests nbconvert nbformat pyyaml

      - name: Convert the Jupyter notebooks
        run: python scripts/render-notebooks.py

      - uses: actions/upload-artifact@v4
        with:
          name: rendered-notebooks
          path: |
            content/blog
            static/blog

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.128.0"
          extended: true
      - name: Build
        run: hugo

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Test - Deploy to this repo GitHub Pages
        if: ${{ github.ref != 'refs/heads/main' }}
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Deploy to live pages site
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          external_repository: adrn/adrn.github.io
          publish_branch: main
          publish_dir: ./public
          cname: adrian.pw
