name: Build site

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    concurrency: build-${{ github.ref }}
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Python dependencies
        run: python -m pip install requests nbconvert nbformat pyyaml

      - name: Convert the Jupyter notebooks
        run: python scripts/render-notebooks.py

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.89.0"
          extended: true
      - name: Build
        run: hugo

      - name: Deploy to production
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          external_repository: adrn/adrn.github.io
          publish_branch: main
          publish_dir: ./public
          cname: adrian.pw

      - name: Deploy to test
        if: ${{ github.ref != 'refs/heads/main' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
